sonar.projectKey=FancySafeBot_fsb-library
sonar.organization=fancysafebot
sonar.projectName=fsb-library

sonar.exclusions=docs/**
sonar.lang.patterns.c="*.c"

sonar.language=cpp

sonar.cfamily.build-wrapper-output=bw-output
sonar.sourceEncoding=UTF-8
